services:

  app:
    build: 
      context: ./docker/php-fpm
    image: api-laravel_place
    container_name: API_bande_Recharge
    restart: unless-stopped
    volumes:
      - ./:/var/www/API_VUE
    environment:
      - APP_ENV=prod
    expose:
      - 9000
    # ports:  # Utilise 'ports' pour rendre le port accessible depuis l'hôte
    #   - "8000:9000"  # Expose le port 9000 du conteneur sur le port 8000 de l'hôte
    # depends_on:
      - db

    networks:
      - backend-network

  server:
    image: nginx:1.26.0-alpine
    container_name: nginx-webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/API_VUE
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - '8084:80'
    depends_on:
      - app

    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin2
    ports:
      - 8083:80
    networks:
      - backend-network

   
  # pour stocker les resultats des requetes frequentes ou les sessions, je l'utilise pour les files d'attentes.
  redis:
    image: redis:alpine
    container_name: redis_2
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - backend-network

  db:
    image: mysql
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: loading_places

    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql 

    networks:
      - backend-network


volumes:
  db_data:

 # un réseau pour permettre la communication entre services
networks:
  backend-network: 

